import 'package:flutter/material.dart';

class Inspire extends StatefulWidget {
  const Inspire({Key? key}) : super(key: key);

  @override
  _InspireState createState() => _InspireState();
}

class _InspireState extends State<Inspire> {
  int _index = 0;
  List quoteList = [
    "We cannot solve problems with the kind of thinking we employed when we came up with them. — Albert Einstein",
    "Learn as if you will live forever, live like you will die tomorrow. — Mahatma Gandhi",
    "Stay away from those people who try to disparage your ambitions. Small minds will always do that, but great minds will give you a feeling that you can become great too. — Mark Twain",
    "When you give joy to other people, you get more joy in return. You should give a good thought to happiness that you can give out. — Eleanor Roosevelt",
    "When you change your thoughts, remember to also change your world.—Norman Vincent Peale",
    "It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest. —Walter Anderson",
    "Nature has given us all the pieces required to achieve exceptional wellness and health, but has left it to us to put these pieces together. —Diane McLaren",
    "Success is not final; failure is not fatal: It is the courage to continue that counts. — Winston S. Churchill",
    "It is better to fail in originality than to succeed in imitation. — Herman ",
    "The road to success and the road to failure are almost exactly the same. — Colin R. Davis",
    "Success usually comes to those who are too busy looking for it. — Henry David Thoreau",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. —Dale Carnegie",
    "Nothing in the world can take the place of Persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. The slogan 'Press On' has solved and always will solve the problems of the human race. —Calvin Coolidge ",
    "There are three ways to ultimate success: The first way is to be kind. The second way is to be kind. The third way is to be kind. —Mister Rogers",
    "Success is peace of mind, which is a direct result of self-satisfaction in knowing you made the effort to become the best of which you are capable. —John Wooden",
    "I never dreamed about success. I worked for it. —Estée Lauder",
    "Success is getting what you want, happiness is wanting what you get. ―W. P. Kinsella",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. — Winston Churchill",
    "Don’t let yesterday take up too much of today. — Will Rogers ",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character. — Unknown ",
    "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. — Steve Jobs",
    "Experience is a hard teacher because she gives the test first, the lesson afterwards. ―Vernon Sanders Law ",
    "To know how much there is to know is the beginning of learning to live. —Dorothy West",
    "Goal setting is the secret to a compelling future. — Tony Robbins",
    "Concentrate all your thoughts upon the work in hand. The sun's rays do not burn until brought to a focus.  — Alexander Graham Bell",
    "Either you run the day or the day runs you. — Jim Rohn",
    "I’m a greater believer in luck, and I find the harder I work the more I have of it. — Thomas Jefferson",
    "When we strive to become better than we are, everything around us becomes better too. — Paulo Coelho ",
    "Opportunity is missed by most people because it is dressed in overalls and looks like work. — Thomas Edison",
    "Setting goals is the first step in turning the invisible into the visible. — Tony Robbins",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it. — Steve Jobs",
    "It’s not about better time management. It’s about better life management — Alexandra of The Productivity Zone",
    "Women challenge the status quo because we are never it. — Cindy Gallop",
    "We don’t just sit around and wait for other people. We just make, and we do. — Arlan Hamilton ",
    "Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. — Oprah Winfrey ",
    "The strongest actions for a woman is to love herself, be herself and shine amongst those who never believed she could. — Unknown",
    "Whenever you see a successful woman, look out for three men who are going out of their way to try to block her. – Yulia Tymoshenko",
    "Some women choose to follow men, and some choose to follow their dreams. If you’re wondering which way to go, remember that your career will never wake up and tell you that it doesn’t love you anymore. — Lady Gaga",
    "The thing women have yet to learn is nobody gives you power. You just take it.  ― Roseanne Barr",
    "A witty woman is a treasure; a witty beauty is a power. ― George Meredith ",
    "When a woman becomes her own best friend life is easier – Diane Von Furstenberg ",
    "If you want something said, ask a man; if you want something done, ask a woman. – Margaret Thatcher",
    "We need women at all levels, including the top, to change the dynamic, reshape the conversation, to make sure women’s voices are heard and heeded, not overlooked and ignored. – Sheryl Sandberg",
    "It took me quite a long time to develop a voice, and now that I have it, I am not going to be silent. – Madeleine Albright",
    "Women must learn to play the game as men do. – Eleanor Roosevelt ",
    "I swear, by my life and my love of it, that I will never live for the sake of another man, nor ask another man to live for mine. — Ayn Rand ",
    "The elevator to success is out of order. You’ll have to use the stairs, one step at a time. — Joe Girard",
    "Be a positive energy trampoline – absorb what you need and rebound more back. — Dave Carolan",
    "People often say that motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily. — Zig Ziglar",
    "Work until your bank account looks like a phone number. — Unknown ",
    "I am so clever that sometimes I don’t understand a single word of what I am saying. — Oscar Wilde",
    "People say nothing is impossible, but I do nothing every day. — Winnie the Pooh",
    "Life is like a sewer… what you get out of it depends on what you put into it. — Tom Lehrer",
    "I always wanted to be somebody, but now I realise I should have been more specific. — Lily Tomlin",
    "Just one small positive thought in the morning can change your whole day. — Dalai Lama",
    "Opportunities don't happen, you create them. — Chris Grosser",
    "Love your family, work super hard, live your passion. — Gary Vaynerchuk",
    "It is never too late to be what you might have been. — George Eliot",
    "Don't let someone else's opinion of you become your reality — Les Brown",
    "If you’re not positive energy, you’re negative energy Mark Cuban",
    "I am not a product of my circumstances. I am a product of my decisions. — Stephen R. Covey",
    "The greatest discovery of my generation is that a human being can alter his life by altering his attitudes. — William James",
    "One of the differences between some successful and unsuccessful people is that one group is full of doers, while the other is full of wishers. — Edmond Mbiaka",
    "I’d rather regret the things I’ve done than regret the things I haven’t done. —Lucille Ball",
    "You cannot plow a field by turning it over in your mind. To begin, begin. ―Gordon B. Hinckley",
    "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love… – Marcus Aurelius",
    "Mondays are the start of the work week which offer new beginnings 52 times a year! – David Dweck",
    "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice. – Wayne Dyer",
    "Your Monday morning thoughts set the tone for your whole week. See yourself getting stronger, and living a fulfilling, happier & healthier life. – Germany Kent ",
    "Friday sees more smiles than any other day of the workweek!—Kate Summers",
    "Oh! It’s Friday again. Share the love that was missing during the week. In a worthy moment of peace and bliss. —S. O’Sade",
    "Every Friday, I like to high five myself for getting through another week on little more than caffeine, willpower, and inappropriate humor. —Nanea Hoffman",
    "Make a Friday a day to celebrate work well done that you can be proud of knowing that you just didn’t put in time to the next paycheck. —Byron Pulsifer",
    "When you leave work on Friday, leave work. Don’t let technology follow you throughout your weekend (answering text messages and emails) take a break you will be more refreshed to begin the workweek if you have had a break. —Catherine Pulsifer",
    "You can get everything in life you want if you will just help enough other people get what they want. —Zig Ziglar",
    "Inspiration does exist, but it must find you working. —Pablo Picasso",
    "Don't settle for average. Bring your best to the moment. Then, whether it fails or succeeds, at least you know you gave all you had. —Angela Bassett",
    "Show up, show up, show up, and after a while the muse shows up, too. —Isabel Allende",
    "Don't bunt. Aim out of the ballpark. Aim for the company of immortals. ―David Ogilvy",
    "I have stood on a mountain of no’s for one yes. —Barbara Elaine Smith",
    "If you believe something needs to exist, if it's something you want to use yourself, don't let anyone ever stop you from doing it. —Tobias Lütke",
    "Don't look at your feet to see if you are doing it right. Just dance. ―Anne Lamott",
    "Someone's sitting in the shade today because someone planted a tree a long time ago. —Warren Buffet",
    "True freedom is impossible without a mind made free by discipline. ―Mortimer J. Adler",
    "Rivers know this: there is no hurry. We shall get there some day. ―A.A. Milne",
    "There is a vitality, a life force, an energy, a quickening that is translated through you into action, and because there is only one of you in all time, this expression is unique. And if you block it, it will never exist through any other medium and will be lost. ―Martha Graham",
    "Small is not just a stepping-stone. Small is a great destination itself. ―Jason Fried",
    "He that can have patience can have what he will. ―Benjamin Franklin",
    "The only one who can tell you “you can’t win” is you and you don’t have to listen. —Jessica Ennis",
    "Set your goals high, and don’t stop till you get there. —Bo Jackson",
    "Take your victories, whatever they may be, cherish them, use them, but don’t settle for them. —Mia Hamm",
    "Life can be much broader once you discover one simple fact: Everything around you that you call life was made up by people that were no smarter than you. And you can change it, you can influence it… Once you learn that, you'll never be the same again. —Steve Jobs",
    "Life is like riding a bicycle. To keep your balance you must keep moving. —Albert Einstein",
    "What you do speaks so loudly that I cannot hear what you say. —Ralph Waldo Emerson",
    "I have never let my schooling interfere with my education. —Mark Twain",
    "If you can't yet do great things, do small things in a great way. ―Napoleon Hill",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse. ―Jim Rohn",
    "Be sure you put your feet in the right place, then stand firm. ―Abraham Lincoln",
    "Live out of your imagination, not your history. —Stephen Covey",
    "Do not wait for the perfect time and place to enter, for you are already onstage. —Unknown",
    "The greater the difficulty, the more the glory in surmounting it. ―Epicurus",
    "Courage doesn't always roar. Sometimes courage is a quiet voice at the end of the day saying, I will try again tomorrow. —Mary Anne Radmacher",
    "If the decisions you make about where you invest your blood, sweat, and tears are not consistent with the person you aspire to be, you’ll never become that person. ―Clayton M. Christensen",
    "Fear of what other people will think is the single most paralyzing dynamic in business and in life. The best moment of my life was the day I realized that I no longer give a damn what anybody thinks. That’s enormously liberating and freeing, and it’s the only way to live your life and do your business — Cindy Gallop",
    "The only way of discovering the limits of the possible is to venture a little way past them into the impossible. ―Arthur C. Clarke",
    "Worry is a misuse of imagination. —Unknown ",
    "Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently. ―Maya Angelou ",
    "I never look back, darling. It distracts from the now. —Edna Mode",
    "A year from now you will wish you had started today. —Unknown",
    "The reason we struggle with insecurity is because we compare our behind-the-scenes with everyone else’s highlight reel. —Steve Furtick",
    "Somewhere, something incredible is waiting to be known. —Carl Sagan",
    "I will not lose, for even in defeat, there’s a valuable lesson learned, so it evens up for me. —Jay-Z",
    "I do not try to dance better than anyone else. I only try to dance better than myself. —Arianna Huffington",
    "If you don’t risk anything, you risk even more. —Erica Jong",
    "The two most important days in your life are the day you’re born and the day you find out why. – Mark Twain",
    "Nothing ever goes away until it teaches us what we need to know. – Pema Chodron",
    "We can see through others only when we can see through ourselves. – Bruce Lee",
    "First forget inspiration. Habit is more dependable. Habit will sustain you whether you're inspired or not. Habit will help you finish and polish your stories. Inspiration won't. Habit is persistence in practice. ―Octavia Butler",
    "The best way out is always through.” ―Robert Frost",
    "The battles that count aren't the ones for gold medals. The struggles within yourself—the invisible, inevitable battles inside all of us—that's where it's at. —Jesse Owens",
    "If there is no struggle, there is no progress.” —Frederick Douglass",
    "Someone will declare, “I am the leader!” and expect everyone to get in line and follow him or her to the gates of heaven or hell. My experience is that it doesn’t happen that way. Others follow you based on the quality of your actions rather than the magnitude of your declarations. ―Bill Walsh",
    "Courage is like a muscle. We strengthen it by use. —Ruth Gordo",
    "Relentlessly prune bullshit, don't wait to do things that matter, and savor the time you have. That's what you do when life is short. —Paul Graham",
    "More is lost by indecision than wrong decision. —Marcus Tullius Cicero",
    "If the highest aim of a captain were to preserve his ship, he would keep it in port forever. —Thomas Aquinas",
    "You can be the ripest, juiciest peach in the world, and there's still going to be somebody who hates peaches. —Dita Von Teese",
    "Keep a little fire burning; however small, however hidden. ―Cormac McCarthy",
    "You’ll never get bored when you try something new. There’s really no limit to what you can do. — Dr. Seuss",
    "I think it’s intoxicating when somebody is so unapologetically who they are. —Don Cheadle",
    "You can never leave footprints that last if you are always walking on tiptoe. —Leymah Gbowee",
    "If you don’t like the road you’re walking, start paving another one. —Dolly Parton",
    "If it makes you nervous, you’re doing it right. —Childish Gambino",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. —Jane Goodall",
    "I choose to make the rest of my life the best of my life. —Louise Hay",
    "In order to be irreplaceable one must always be different. —Coco Chanel",
    "Anything can make me stop and look and wonder, and sometimes learn. —Kurt Vonnegut",
    "People's passion and desire for authenticity is strong. —Constance Wu",
    "A surplus of effort could overcome a deficit of confidence. —Sonia Sotomayor",
    "Doubt is a killer. You just have to know who you are and what you stand for. —Jennifer Lopez",
    "No one changes the world who isn’t obsessed. —Billie Jean King",
    "I learned a long time ago that there is something worse than missing the goal, and that’s not pulling the trigger. —Mia Hamm",
    "Some people want it to happen, some wish it would happen, others make it happen. —Michael Jordan",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.amberAccent[200],
        child: Expanded(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Spacer(),
              Padding(
                padding: const EdgeInsets.all(10.0),
                child: Image.network('https://picsum.photos/300/250'),
              ),
              Container(
                margin: EdgeInsets.all(30.0),
                child: Center(child: Text(quoteList[_index % quoteList.length],
                style: TextStyle(fontSize: 20)))),
              Divider(
                thickness: 3.3,
                height: 20,
              ),
              SizedBox(
                height: 30,
              ),
              Padding(
                padding: const EdgeInsets.all(10.0),
                child: ElevatedButton(
                  onPressed: () {
                    _quotes();
                  },
                  child: Text(
                    'Stay Inspired',
                    style: TextStyle(
                      color: Colors.green[500],
                      fontStyle: FontStyle.italic,
                      fontWeight: FontWeight.bold,
                      fontSize: 32,
                    ),
                  ),
                  style: ElevatedButton.styleFrom(primary: Colors.white),
                ),
              ),
              Spacer(),
            ],
          ),
        ),
      ),
    );
  }

  void _quotes() {
    setState(() {
      _index++;
    });
  }
}
